version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: pg-finance
    restart: always
    environment:
      POSTGRES_USER: finance
      POSTGRES_PASSWORD: financepass
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
